version: 0.0
os: linux

files:
  - source: frontend/dist
    destination: /var/www/chaekdam

  - source: bookapp/build/libs
    destination: /opt/chaekdam

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
      runas: root
